name: Deploy 4sacs.fr to Freebox (optimized tar)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tar archive
        run: |
          echo "Création de l'archive tar.gz..."
          tar -czf site_static.tar.gz -C site_static .

      - name: Upload site archive via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          source: "site_static.tar.gz"
          target: "/opt/docker/sacs"

      - name: Extract archive and deploy on Freebox
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            echo "Nettoyage du dossier cible..."
            sudo rm -rf /opt/docker/sacs/html
            sudo mkdir -p /opt/docker/sacs/html
            sudo chown -R $USER:$USER /opt/docker/sacs/html
            sudo chmod -R 755 /opt/docker/sacs/html

            echo "Extraction de l'archive..."
            cd /opt/docker/sacs
            tar -xzf site_static.tar.gz -C html
            rm site_static.tar.gz

            echo "Redémarrage du conteneur Nginx (sacs)..."
            docker compose restart sacs